version: '3.8'

services:
  mouad-java:
    build: .
    container_name: mouad-java-container
    ports:
      - "1015:8080"
    networks:
      - mouad-net
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres-sql

  postgres-sql:
    image: postgres
    container_name: postgres-sql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: mouad-demo
    ports:
      - "1001:5050"
    networks:
      - mouad-net

networks:
  mouad-net:
    driver: bridge
